default: &default
  adapter: postgresql
  encoding: unicode
  username: luis
  password: luis123
  host: localhost

development:
  <<: *default
  database: gaming

test:
  <<: *default
  database: gaming_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>