default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: gardy
  port: 5433

development:
  <<: *default
  database: gaming
  username: postgres
  password: gardy
  port: 5433

test:
  <<: *default
  database: <%= ENV["DB_NAME_TEST"] %>

production:
  <<: *default
  database: gaming
  username: postgres
  password: gardy
  port: 5433
